package sftpadmin

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"
)

// Shared validator-parity fixtures (tasks 1.1, 3.3). These are real keys
// generated by ssh-keygen; the same literals appear in
// test/sftp-reconcile.sh, where the shell reconciler must accept them.
// Expected fingerprints come from `ssh-keygen -l -E sha256`.
const (
	fixtureEd25519   = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILHuWCpBoR+5/l/Sr1njB/PnEPDw98SjgPlB3MEm1i9Z fixture-ed"
	fixtureEd25519FP = "SHA256:YKU2L3Twc9Iw5hGGRbztRqCjUMecG7z7lvut/aDw4B4"

	fixtureRSA   = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCEES+HFIuRQAkSK8MYMv/SpwmojyaETDeAfvXFdp46rY2MkSOXZBC1amcVXJD9sPYdda2055eD5U+J3tuTCCPnGwXjGm4AeSmv1D9gkah/35GOgxHcPtodaKtA5xRalhpR8GHyJ99QDar+gOaK6kg3AnmkgM85XGur27+Pq1UWH6D9cSauuda9iS+xy+njmPOUnSKYNWQel5jGzTrpaEPVwxSPFNWZFhht1xG4zWKxkxMrnPXcF8/DKkzUWhUncwdf3OUZ38WAvYKGPvPSmeSDlm1bC6kc8vatkE+39UED4hW5Z9J7DSg1XDh66Wgc7foGZzn+e6jMYgyTE5Y3RCPl fixture-rsa"
	fixtureRSAFP = "SHA256:wdmGFfl0aM1+Eh2u69zGQkLB0BhV9DhcdzBRQ7kec/M"

	fixtureECDSA   = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBJlS0JDnX4YX/ybI5cLciJ5MjTNV62EoRC8pwf9vAUKKhFpZCMgBfiubwWfTOid4gmvjMr0h546f1JrBQhHJTw= fixture-ec"
	fixtureECDSAFP = "SHA256:si/rfbJIIhc1Okq/pGsQYmwBTnxx77aVbvPzrxR/ZwI"
)

// seedRawManifest overwrites the store file with doc for legacy/malformed
// fixtures that ordinary strict writes would refuse.
func seedRawManifest(t *testing.T, srv *Server, doc string) {
	t.Helper()
	if err := os.WriteFile(srv.store.Path(), []byte(doc), 0o600); err != nil {
		t.Fatal(err)
	}
}

func rawManifest(t *testing.T, srv *Server) string {
	t.Helper()
	raw, err := os.ReadFile(srv.store.Path())
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

func mustKeys(t *testing.T, srv *Server, username string) (keys []string, enabled bool) {
	t.Helper()
	m, err := srv.store.Load()
	if err != nil {
		t.Fatal(err)
	}
	for _, u := range m.Users {
		if u.Username == username {
			return u.AuthorizedKeys, u.Enabled
		}
	}
	t.Fatalf("user %q not in manifest %+v", username, m)
	return nil, false
}

// TestFingerprintMatchesSshKeygen pins the canonical wire-blob fingerprint
// against ssh-keygen output; comments and whitespace must not affect it.
func TestFingerprintMatchesSshKeygen(t *testing.T) {
	for name, tc := range map[string]struct{ key, want string }{
		"ed25519": {fixtureEd25519, fixtureEd25519FP},
		"rsa":     {fixtureRSA, fixtureRSAFP},
		"ecdsa":   {fixtureECDSA, fixtureECDSAFP},
	} {
		fp, err := FingerprintOf(tc.key)
		if err != nil {
			t.Errorf("%s: FingerprintOf = %v", name, err)
			continue
		}
		if fp != tc.want {
			t.Errorf("%s: fingerprint = %q, want %q", name, fp, tc.want)
		}
		// Comments and surrounding whitespace do not affect identity.
		bare := strings.Join(strings.Fields(tc.key)[:2], " ")
		for _, variant := range []string{
			bare + " another-comment",
			"  " + tc.key + "  ",
			"\t" + bare + "\t",
		} {
			fp2, err := FingerprintOf(variant)
			if err != nil {
				t.Errorf("%s: FingerprintOf(%q) = %v", name, variant, err)
				continue
			}
			if fp2 != tc.want {
				t.Errorf("%s: FingerprintOf(%q) = %q, want %q", name, variant, fp2, tc.want)
			}
		}
	}
}

// TestValidatorParityMatrix keeps the Admin allowlist aligned with the
// shell reconciler's: every accepted key must also match the shell shape,
// every rejected input must fail closed on both sides.
func TestValidatorParityMatrix(t *testing.T) {
	accept := map[string]string{
		"ed25519":    fixtureEd25519,
		"rsa":        fixtureRSA,
		"ecdsa":      fixtureECDSA,
		"comment":    strings.Join(strings.Fields(fixtureEd25519)[:2], " ") + " extra comment with spaces",
		"whitespace": "  \t" + fixtureRSA + "  ",
	}
	for name, key := range accept {
		if _, _, err := ValidatePublicKey(key); err != nil {
			t.Errorf("accept %s: ValidatePublicKey = %v", name, err)
		}
	}
	reject := map[string]string{
		"empty":       "",
		"spaces":      "   ",
		"garbage":     "not-a-key",
		"one field":   "ssh-ed25519",
		"unsupported": "ssh-dss AAAAC3NzaC1kc3MAAA== x",
		"bad base64":  "ssh-ed25519 !!!not-base64!!! x",
		"truncated":   "ssh-ed25519 AAAACw== x",
		"mismatch":    "ssh-rsa " + strings.Fields(fixtureEd25519)[1] + " x",
		"multiline":   "ssh-ed25519 AAAA\nssh-ed25519 BBBB",
		"private":     "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----",
	}
	for name, key := range reject {
		if _, _, err := ValidatePublicKey(key); err == nil {
			t.Errorf("reject %s: ValidatePublicKey = nil, want error", name)
		}
		if _, err := FingerprintOf(key); err == nil {
			t.Errorf("reject %s: FingerprintOf = nil, want error", name)
		}
	}
}

func TestValidFingerprintShape(t *testing.T) {
	for _, fp := range []string{fixtureEd25519FP, fixtureRSAFP, fixtureECDSAFP} {
		if !ValidFingerprint(fp) {
			t.Errorf("ValidFingerprint(%q) = false, want true", fp)
		}
	}
	for name, fp := range map[string]string{
		"empty":      "",
		"no prefix":  strings.TrimPrefix(fixtureEd25519FP, "SHA256:"),
		"md5 prefix": "MD5:aa:bb:cc",
		"padded":     fixtureEd25519FP + "=",
		"spaces":     "SHA256:ab cd",
		"short":      "SHA256:abc",
	} {
		if ValidFingerprint(fp) {
			t.Errorf("ValidFingerprint %s (%q) = true, want false", name, fp)
		}
	}
}

// TestStoreRemoveInvalidKeys covers task 1.2: manifest-wide repair under
// the store lock with strict ordinary updates preserved.
func TestStoreRemoveInvalidKeys(t *testing.T) {
	t.Run("mixed users repaired, valid preserved", func(t *testing.T) {
		st := tempStore(t)
		if err := os.MkdirAll(tmpDirOf(st), 0o700); err != nil {
			t.Fatal(err)
		}
		doc := `{"version":1,"users":[` +
			`{"username":"alice","enabled":true,"authorized_keys":["` + canonOf(t, fixtureEd25519) + `","nope"]},` +
			`{"username":"bob","enabled":true,"authorized_keys":["` + canonOf(t, fixtureRSA) + `"]}]}`
		if err := os.WriteFile(st.Path(), []byte(doc), 0o600); err != nil {
			t.Fatal(err)
		}
		rep, err := st.RemoveInvalidKeys()
		if err != nil {
			t.Fatalf("RemoveInvalidKeys = %v", err)
		}
		if rep.RemovedKeys != 1 {
			t.Errorf("removed = %d, want 1", rep.RemovedKeys)
		}
		m, err := st.Load()
		if err != nil {
			t.Fatal(err)
		}
		for _, u := range m.Users {
			switch u.Username {
			case "alice":
				if !u.Enabled || len(u.AuthorizedKeys) != 1 {
					t.Errorf("alice = %+v, want enabled with 1 valid key", u)
				}
				if _, fp, _ := ValidatePublicKey(u.AuthorizedKeys[0]); fp != fixtureEd25519FP {
					t.Errorf("alice key fingerprint = %q, want %q", fp, fixtureEd25519FP)
				}
			case "bob":
				if !u.Enabled || len(u.AuthorizedKeys) != 1 {
					t.Errorf("bob = %+v, want untouched", u)
				}
			}
		}
	})

	t.Run("two users with invalid entries both repaired", func(t *testing.T) {
		st := tempStore(t)
		mustWriteDoc(t, st, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["bad1"]},`+
			`{"username":"bob","enabled":false,"authorized_keys":["`+canonOf(t, fixtureRSA)+`","bad2"]}]}`)
		rep, err := st.RemoveInvalidKeys()
		if err != nil {
			t.Fatalf("RemoveInvalidKeys = %v", err)
		}
		if rep.RemovedKeys != 2 {
			t.Errorf("removed = %d, want 2", rep.RemovedKeys)
		}
		m, _ := st.Load()
		for _, u := range m.Users {
			if u.Username == "alice" {
				if u.Enabled || len(u.AuthorizedKeys) != 0 {
					t.Errorf("alice = %+v, want disabled with empty keys", u)
				}
			}
			if u.Username == "bob" {
				if u.Enabled || len(u.AuthorizedKeys) != 1 {
					t.Errorf("bob = %+v, want still disabled with 1 valid key", u)
				}
			}
		}
	})

	t.Run("all-invalid user becomes disabled with valid empty keys", func(t *testing.T) {
		st := tempStore(t)
		mustWriteDoc(t, st, `{"version":1,"users":[{"username":"solo","enabled":true,"authorized_keys":["junk"]}]}`)
		if _, err := st.RemoveInvalidKeys(); err != nil {
			t.Fatal(err)
		}
		m, _ := st.Load()
		if m.Users[0].Enabled || len(m.Users[0].AuthorizedKeys) != 0 {
			t.Fatalf("solo = %+v, want disabled with valid empty keys", m.Users[0])
		}
		if err := st.Update(func(_ *Manifest) error { return nil }); err != nil {
			t.Fatalf("repaired manifest must pass strict Update, got %v", err)
		}
	})

	t.Run("no-op repair leaves file untouched", func(t *testing.T) {
		st := tempStore(t)
		mustWriteDoc(t, st, `{"version":1,"users":[{"username":"ok","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`"]}]}`)
		before, _ := os.ReadFile(st.Path())
		rep, err := st.RemoveInvalidKeys()
		if err != nil {
			t.Fatal(err)
		}
		if rep.RemovedKeys != 0 {
			t.Errorf("removed = %d, want 0", rep.RemovedKeys)
		}
		after, _ := os.ReadFile(st.Path())
		if string(before) != string(after) {
			t.Error("no-op repair rewrote the manifest file")
		}
	})

	t.Run("valid empty user stays enabled", func(t *testing.T) {
		st := tempStore(t)
		mustWriteDoc(t, st, `{"version":1,"users":[{"username":"empty","enabled":true,"authorized_keys":[]}]}`)
		if _, err := st.RemoveInvalidKeys(); err != nil {
			t.Fatal(err)
		}
		m, _ := st.Load()
		if !m.Users[0].Enabled {
			t.Error("valid-empty user must stay enabled after repair")
		}
	})
}

func tmpDirOf(st *Store) string {
	return st.Path()[:len(st.Path())-len("/users.json")]
}

func canonOf(t *testing.T, key string) string {
	t.Helper()
	canon, _, err := ValidatePublicKey(key)
	if err != nil {
		t.Fatal(err)
	}
	return canon
}

func mustWriteDoc(t *testing.T, st *Store, doc string) {
	t.Helper()
	if err := os.MkdirAll(tmpDirOf(st), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(st.Path(), []byte(doc), 0o600); err != nil {
		t.Fatal(err)
	}
}

// TestDeleteKeyHandler covers task 2.1 plus final-key disablement (2.4).
func TestDeleteKeyHandler(t *testing.T) {
	newSeeded := func(t *testing.T) (*Server, *http.Cookie, string) {
		t.Helper()
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`","`+canonOf(t, fixtureRSA)+`"]},`+
			`{"username":"solo","enabled":true,"authorized_keys":["`+canonOf(t, fixtureECDSA)+`"]}]}`)
		return srv, sess, csrf
	}
	del := func(srv *Server, sess *http.Cookie, csrf, username, fp string) *httptest.ResponseRecorder {
		return authedPost(srv, sess, "/users/delete-key", url.Values{
			csrfField:     {csrf},
			"username":    {username},
			"fingerprint": {fp},
		})
	}

	t.Run("unauthenticated is 401", func(t *testing.T) {
		srv, _, _ := newSeeded(t)
		rec := httptest.NewRecorder()
		req := httptest.NewRequest(http.MethodPost, "/users/delete-key",
			strings.NewReader(url.Values{"username": {"alice"}, "fingerprint": {fixtureEd25519FP}}.Encode()))
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		srv.ServeHTTP(rec, req)
		if rec.Code != http.StatusUnauthorized {
			t.Errorf("anon delete = %d, want 401", rec.Code)
		}
	})

	t.Run("bad csrf is 403 without mutation", func(t *testing.T) {
		srv, sess, _ := newSeeded(t)
		before := rawManifest(t, srv)
		if rec := del(srv, sess, "forged", "alice", fixtureEd25519FP); rec.Code != http.StatusForbidden {
			t.Errorf("forged csrf = %d, want 403", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("CSRF-rejected delete mutated the manifest")
		}
	})

	t.Run("malformed fingerprint is 400", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		for _, fp := range []string{"", "nope", "SHA256:abc", "MD5:aa"} {
			if rec := del(srv, sess, csrf, "alice", fp); rec.Code != http.StatusBadRequest {
				t.Errorf("fingerprint %q = %d, want 400", fp, rec.Code)
			}
		}
	})

	t.Run("unknown user and unknown key are 404 without mutation", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		before := rawManifest(t, srv)
		if rec := del(srv, sess, csrf, "ghost", fixtureEd25519FP); rec.Code != http.StatusNotFound {
			t.Errorf("unknown user = %d, want 404", rec.Code)
		}
		if rec := del(srv, sess, csrf, "alice", fixtureECDSAFP); rec.Code != http.StatusNotFound {
			t.Errorf("unknown key = %d, want 404", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("404 delete mutated the manifest")
		}
	})

	t.Run("removes one key, preserves the other", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		if rec := del(srv, sess, csrf, "alice", fixtureEd25519FP); rec.Code != http.StatusSeeOther {
			t.Fatalf("delete = %d, want 303", rec.Code)
		}
		keys, enabled := mustKeys(t, srv, "alice")
		if !enabled || len(keys) != 1 {
			t.Fatalf("alice keys = %v enabled=%v, want 1 key enabled", keys, enabled)
		}
		if _, fp, _ := ValidatePublicKey(keys[0]); fp != fixtureRSAFP {
			t.Errorf("remaining fingerprint = %q, want %q", fp, fixtureRSAFP)
		}
		// solo untouched.
		if keys, _ := mustKeys(t, srv, "solo"); len(keys) != 1 {
			t.Errorf("solo keys = %d, want untouched 1", len(keys))
		}
	})

	t.Run("repeated delete is 404 without mutation", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		if rec := del(srv, sess, csrf, "alice", fixtureEd25519FP); rec.Code != http.StatusSeeOther {
			t.Fatalf("first delete = %d", rec.Code)
		}
		before := rawManifest(t, srv)
		if rec := del(srv, sess, csrf, "alice", fixtureEd25519FP); rec.Code != http.StatusNotFound {
			t.Errorf("repeated delete = %d, want 404", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("repeated delete mutated the manifest")
		}
	})

	t.Run("final usable key disables with valid empty keys", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		if rec := del(srv, sess, csrf, "solo", fixtureECDSAFP); rec.Code != http.StatusSeeOther {
			t.Fatalf("delete final = %d, want 303", rec.Code)
		}
		keys, enabled := mustKeys(t, srv, "solo")
		if enabled || len(keys) != 0 {
			t.Fatalf("solo keys = %v enabled=%v, want disabled with empty keys", keys, enabled)
		}
		if _, err := srv.store.Load(); err != nil {
			t.Fatalf("post-delete manifest must load: %v", err)
		}
	})

	t.Run("strict conflict with legacy invalid entry is 409", func(t *testing.T) {
		srv, sess, csrf := newSeeded(t)
		seedRawManifest(t, srv, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`","`+canonOf(t, fixtureRSA)+`"]},`+
			`{"username":"legacy","enabled":true,"authorized_keys":["junk"]}]}`)
		before := rawManifest(t, srv)
		if rec := del(srv, sess, csrf, "alice", fixtureEd25519FP); rec.Code != http.StatusConflict {
			t.Errorf("delete blocked by legacy entry = %d, want 409", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("409 delete mutated the manifest")
		}
	})
}

// TestRemoveInvalidKeysHandler covers task 2.2.
func TestRemoveInvalidKeysHandler(t *testing.T) {
	post := func(srv *Server, sess *http.Cookie, csrf string) *httptest.ResponseRecorder {
		return authedPost(srv, sess, "/users/remove-invalid-keys", url.Values{csrfField: {csrf}})
	}

	t.Run("unauthenticated is 401, bad csrf is 403", func(t *testing.T) {
		srv := newTestServer(t)
		rec := httptest.NewRecorder()
		req := httptest.NewRequest(http.MethodPost, "/users/remove-invalid-keys", nil)
		srv.ServeHTTP(rec, req)
		if rec.Code != http.StatusUnauthorized {
			t.Errorf("anon repair = %d, want 401", rec.Code)
		}
		sess, _ := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[]}`)
		before := rawManifest(t, srv)
		if rec := authedPost(srv, sess, "/users/remove-invalid-keys",
			url.Values{csrfField: {"forged"}}); rec.Code != http.StatusForbidden {
			t.Errorf("forged csrf = %d, want 403", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("CSRF-rejected repair mutated the manifest")
		}
	})

	t.Run("two-user repair preserves valid and unrelated fields", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`","bad1"]},`+
			`{"username":"bob","enabled":false,"authorized_keys":["bad2","`+canonOf(t, fixtureRSA)+`"]}]}`)
		if rec := post(srv, sess, csrf); rec.Code != http.StatusSeeOther {
			t.Fatalf("repair = %d, want 303", rec.Code)
		}
		m, err := srv.store.Load()
		if err != nil {
			t.Fatal(err)
		}
		for _, u := range m.Users {
			if u.Username == "alice" && (!u.Enabled || len(u.AuthorizedKeys) != 1) {
				t.Errorf("alice = %+v, want enabled with 1 key", u)
			}
			if u.Username == "bob" && (u.Enabled || len(u.AuthorizedKeys) != 1) {
				t.Errorf("bob = %+v, want still disabled with 1 key", u)
			}
		}
	})

	t.Run("all-invalid user disabled, no-op is success", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"solo","enabled":true,"authorized_keys":["junk"]}]}`)
		if rec := post(srv, sess, csrf); rec.Code != http.StatusSeeOther {
			t.Fatalf("repair = %d, want 303", rec.Code)
		}
		if keys, enabled := mustKeys(t, srv, "solo"); enabled || len(keys) != 0 {
			t.Fatalf("solo = %v enabled=%v, want disabled empty", keys, enabled)
		}
		before := rawManifest(t, srv)
		if rec := post(srv, sess, csrf); rec.Code != http.StatusSeeOther {
			t.Errorf("no-op repair = %d, want 303", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("no-op repair rewrote the manifest")
		}
	})
}

// TestStatusZeroKeyEnable covers task 2.3: disable retains keys,
// zero-key enable is 409, strict conflicts are 409.
func TestStatusZeroKeyEnable(t *testing.T) {
	flip := func(srv *Server, sess *http.Cookie, csrf, username, action string) int {
		return authedPost(srv, sess, "/users/status", url.Values{
			csrfField: {csrf}, "username": {username}, "action": {action},
		}).Code
	}

	t.Run("disable retains keys, re-enable restores", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`"]}]}`)
		if code := flip(srv, sess, csrf, "alice", "disable"); code != http.StatusSeeOther {
			t.Fatalf("disable = %d", code)
		}
		keys, enabled := mustKeys(t, srv, "alice")
		if enabled || len(keys) != 1 {
			t.Fatalf("disabled alice = %v enabled=%v, want keys retained", keys, enabled)
		}
		if code := flip(srv, sess, csrf, "alice", "enable"); code != http.StatusSeeOther {
			t.Fatalf("enable = %d", code)
		}
		if keys, enabled := mustKeys(t, srv, "alice"); !enabled || len(keys) != 1 {
			t.Errorf("re-enabled alice = %v enabled=%v, want 1 key", keys, enabled)
		}
	})

	t.Run("zero-key enable is 409 without enabling", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"nokeys","enabled":false,"authorized_keys":[]}]}`)
		if code := flip(srv, sess, csrf, "nokeys", "enable"); code != http.StatusConflict {
			t.Errorf("zero-key enable = %d, want 409", code)
		}
		if _, enabled := mustKeys(t, srv, "nokeys"); enabled {
			t.Error("zero-key enable enabled the user")
		}
	})

	t.Run("enable with only invalid keys is 409", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"bad","enabled":false,"authorized_keys":["junk"]}]}`)
		if code := flip(srv, sess, csrf, "bad", "enable"); code != http.StatusConflict {
			t.Errorf("invalid-key enable = %d, want 409", code)
		}
		if _, enabled := mustKeys(t, srv, "bad"); enabled {
			t.Error("invalid-key enable enabled the user")
		}
	})

	t.Run("strict conflict on unrelated invalid entry is 409", func(t *testing.T) {
		srv := newTestServer(t)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`"]},`+
			`{"username":"legacy","enabled":true,"authorized_keys":["junk"]}]}`)
		if code := flip(srv, sess, csrf, "alice", "disable"); code != http.StatusConflict {
			t.Errorf("status blocked by legacy entry = %d, want 409", code)
		}
		if _, enabled := mustKeys(t, srv, "alice"); !enabled {
			t.Error("409 status flip mutated the user")
		}
	})
}

// stubGen returns gen stubbed to the given public keys in order.
func stubGen(pubs ...string) func(string) (KeyPair, error) {
	i := 0
	return func(comment string) (KeyPair, error) {
		pub := pubs[i%len(pubs)]
		i++
		return KeyPair{PublicKey: pub, PrivatePEM: "fake-private-for-" + comment}, nil
	}
}

// TestGenerateKeyHandler covers task 3.1: generated onboarding appends
// without re-enabling and preserves existing keys.
func TestGenerateKeyHandler(t *testing.T) {
	gen := func(srv *Server, sess *http.Cookie, csrf, username string) *httptest.ResponseRecorder {
		return authedPost(srv, sess, "/users/generate-key", url.Values{
			csrfField: {csrf}, "username": {username},
		})
	}

	t.Run("auth, csrf, and user errors", func(t *testing.T) {
		srv := newTestServer(t)
		srv.gen = stubGen(fixtureEd25519)
		rec := httptest.NewRecorder()
		req := httptest.NewRequest(http.MethodPost, "/users/generate-key",
			strings.NewReader(url.Values{"username": {"alice"}}.Encode()))
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		srv.ServeHTTP(rec, req)
		if rec.Code != http.StatusUnauthorized {
			t.Errorf("anon generate = %d, want 401", rec.Code)
		}
		sess, csrf := loginAs(t, srv)
		if rec := authedPost(srv, sess, "/users/generate-key",
			url.Values{csrfField: {"forged"}, "username": {"alice"}}); rec.Code != http.StatusForbidden {
			t.Errorf("forged csrf = %d, want 403", rec.Code)
		}
		if rec := gen(srv, sess, csrf, "ghost"); rec.Code != http.StatusNotFound {
			t.Errorf("unknown user = %d, want 404", rec.Code)
		}
		if rec := gen(srv, sess, csrf, "Bad Name!"); rec.Code != http.StatusBadRequest {
			t.Errorf("malformed username = %d, want 400", rec.Code)
		}
		if rec := gen(srv, sess, csrf, ""); rec.Code != http.StatusBadRequest {
			t.Errorf("empty username = %d, want 400", rec.Code)
		}
	})

	t.Run("generation failure is 500 without mutation", func(t *testing.T) {
		srv := newTestServer(t)
		srv.gen = func(string) (KeyPair, error) { return KeyPair{}, errTestBoom }
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"alice","enabled":true,"authorized_keys":[]}]}`)
		before := rawManifest(t, srv)
		rec := authedPost(srv, sess, "/users/generate-key", url.Values{
			csrfField: {csrf}, "username": {"alice"},
		})
		if rec.Code != http.StatusInternalServerError {
			t.Errorf("failed generation = %d, want 500", rec.Code)
		}
		if after := rawManifest(t, srv); after != before {
			t.Error("failed generation mutated the manifest")
		}
	})

	t.Run("appends distinct keys, preserves existing, no re-enable", func(t *testing.T) {
		srv := newTestServer(t)
		srv.gen = stubGen(fixtureEd25519, fixtureRSA)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[`+
			`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureECDSA)+`"]},`+
			`{"username":"frozen","enabled":false,"authorized_keys":[]}]}`)
		rec := gen(srv, sess, csrf, "alice")
		if rec.Code != http.StatusOK {
			t.Fatalf("generate = %d, want 200", rec.Code)
		}
		if !strings.Contains(rec.Body.String(), fixtureEd25519FP) {
			t.Error("generate page must show the new fingerprint")
		}
		m := tokenRe.FindStringSubmatch(rec.Body.String())
		if m == nil {
			t.Fatal("generate page has no download token")
		}
		keys, enabled := mustKeys(t, srv, "alice")
		if !enabled || len(keys) != 2 {
			t.Fatalf("alice keys = %d enabled=%v, want 2 enabled", len(keys), enabled)
		}
		// Second generation yields a distinct fingerprint.
		rec2 := gen(srv, sess, csrf, "alice")
		if rec2.Code != http.StatusOK {
			t.Fatalf("second generate = %d, want 200", rec2.Code)
		}
		keys, _ = mustKeys(t, srv, "alice")
		if len(keys) != 3 {
			t.Fatalf("alice keys = %d, want 3", len(keys))
		}
		seen := map[string]bool{}
		for _, k := range keys {
			_, fp, err := ValidatePublicKey(k)
			if err != nil {
				t.Fatalf("stored key invalid: %v", err)
			}
			seen[fp] = true
		}
		if len(seen) != 3 {
			t.Errorf("fingerprints = %v, want 3 distinct", seen)
		}
		// Disabled users gain the key but stay disabled.
		if rec := gen(srv, sess, csrf, "frozen"); rec.Code != http.StatusOK {
			t.Fatalf("generate for disabled = %d, want 200", rec.Code)
		}
		if keys, enabled := mustKeys(t, srv, "frozen"); enabled || len(keys) != 1 {
			t.Errorf("frozen = %v enabled=%v, want 1 key still disabled", keys, enabled)
		}
		// Private material never reaches the manifest.
		if strings.Contains(rawManifest(t, srv), "fake-private") {
			t.Error("private key material leaked into the manifest")
		}
	})
}

// TestGeneratedDownloadSemantics covers task 3.2 on the shared pending-key
// flow: single use, TTL, restart invalidation, no-store, no persistence.
func TestGeneratedDownloadSemantics(t *testing.T) {
	newGenerated := func(t *testing.T) (*Server, *http.Cookie, string) {
		t.Helper()
		srv := newTestServer(t)
		srv.gen = stubGen(fixtureEd25519)
		sess, csrf := loginAs(t, srv)
		seedRawManifest(t, srv, `{"version":1,"users":[{"username":"alice","enabled":true,"authorized_keys":[]}]}`)
		rec := authedPost(srv, sess, "/users/generate-key", url.Values{
			csrfField: {csrf}, "username": {"alice"},
		})
		if rec.Code != http.StatusOK {
			t.Fatalf("generate = %d", rec.Code)
		}
		m := tokenRe.FindStringSubmatch(rec.Body.String())
		if m == nil {
			t.Fatal("no download token")
		}
		return srv, sess, m[1]
	}
	get := func(srv *Server, sess *http.Cookie, token string) *httptest.ResponseRecorder {
		r := httptest.NewRecorder()
		q := httptest.NewRequest(http.MethodGet, "/keys/download?token="+token, nil)
		q.AddCookie(sess)
		srv.ServeHTTP(r, q)
		return r
	}

	t.Run("first download 200 with no-store, second 404", func(t *testing.T) {
		srv, sess, token := newGenerated(t)
		first := get(srv, sess, token)
		if first.Code != http.StatusOK {
			t.Fatalf("first download = %d, want 200", first.Code)
		}
		if got := first.Header().Get("Cache-Control"); got != "no-store" {
			t.Errorf("Cache-Control = %q, want no-store", got)
		}
		if !strings.Contains(first.Body.String(), "fake-private-for-alice") {
			t.Error("downloaded body is not the generated private key")
		}
		if second := get(srv, sess, token); second.Code != http.StatusNotFound {
			t.Errorf("second download = %d, want 404", second.Code)
		}
	})

	t.Run("unknown and expired tokens are 404", func(t *testing.T) {
		srv, sess, token := newGenerated(t)
		if rec := get(srv, sess, "does-not-exist"); rec.Code != http.StatusNotFound {
			t.Errorf("unknown token = %d, want 404", rec.Code)
		}
		srv.mu.Lock()
		pk := srv.pending[token]
		pk.expires = time.Now().Add(-time.Minute)
		srv.pending[token] = pk
		srv.mu.Unlock()
		if rec := get(srv, sess, token); rec.Code != http.StatusNotFound {
			t.Errorf("expired token = %d, want 404", rec.Code)
		}
	})

	t.Run("restart invalidates pending downloads", func(t *testing.T) {
		srv, sess, token := newGenerated(t)
		restarted := NewServer(Config{Password: testPassword, UsersFile: srv.store.Path()}, srv.store)
		if rec := get(restarted, sess, token); rec.Code == http.StatusOK {
			t.Error("post-restart download succeeded, want rejection")
		}
		// The restarted server shares the store: the public key survived.
		if keys, _ := mustKeys(t, restarted, "alice"); len(keys) != 1 {
			t.Errorf("post-restart alice keys = %d, want 1", len(keys))
		}
	})
}

// TestAddKeyStrictConflict extends task 3.3: the advanced endpoint stays
// compatible but reports strict-manifest conflicts as 409.
func TestAddKeyStrictConflict(t *testing.T) {
	srv := newTestServer(t)
	sess, csrf := loginAs(t, srv)
	seedRawManifest(t, srv, `{"version":1,"users":[`+
		`{"username":"alice","enabled":true,"authorized_keys":["`+canonOf(t, fixtureEd25519)+`"]},`+
		`{"username":"legacy","enabled":true,"authorized_keys":["junk"]}]}`)
	code := authedPost(srv, sess, "/users/add-key", url.Values{
		csrfField:    {csrf},
		"username":   {"alice"},
		"public_key": {fixtureRSA},
	}).Code
	if code != http.StatusConflict {
		t.Errorf("add-key blocked by legacy entry = %d, want 409", code)
	}
	// Validator-parity fixture: an RSA key registers cleanly once repaired.
	if _, err := srv.store.RemoveInvalidKeys(); err != nil {
		t.Fatal(err)
	}
	code = authedPost(srv, sess, "/users/add-key", url.Values{
		csrfField:    {csrf},
		"username":   {"alice"},
		"public_key": {fixtureRSA},
	}).Code
	if code != http.StatusSeeOther {
		t.Errorf("add-key after repair = %d, want 303", code)
	}
	if keys, _ := mustKeys(t, srv, "alice"); len(keys) != 2 {
		t.Errorf("alice keys = %d, want 2", len(keys))
	}
}
